version: '3.9'

services:
  db:
    image: postgres:16.3
    restart: always
    container_name: mgv-hub-postgres
    environment:
      POSTGRES_DB: ${DB_NAME:-mgv_hub_db}
      POSTGRES_USER: ${DB_USER:-mgv_user}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-mgv_password}
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  db_data: